### ISSUE TITLE
Latest deployed not work?

### ISSUE THREAD

**Issue by leepupu** [jmmk/clash-attack-sim#17]
Chrome 43
http://jmmk.github.io/clash-attack-sim/

Got Error: Minified exception occurred;
![Error: Minified exception occurred](http://i.imgur.com/vKHPhL3.png)

**Comment by jmmk** [comment]
Yeah it's broken and I didn't revert it because I thought I would have time to fix it.

Unfortunately, I am without access to a computer for the next two weeks, so I won't be able to fix it

**Comment by jmmk** [comment]
Everything should be working again. Thanks!
